### ISSUE TITLE
Review data value access methods

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/emohawk#14]
At the moment on a (GRIB) fieldlist we can use:

- values: it is a property, for a single field it returns a 1D ndarray, while for multiple fields a 2D ndarray

- to_numpy(flatten=True): similar to values. However, if flatten=False for each field having Ni, Nj  returns a 2D ndarray 

The question is if we want to keep values.

**Comment by JamesVarndell** [comment]
It looks like the `values` property is used extensively in other methods of emohawk classes, and it possibly makes sense to keep it separate from `to_numpy` so that we have an internal property for handling data values that we can tweak without worrying about the core user API. With this in mind, I would propose keeping the property but giving it a private name (`_values`). What do you think @sandorkertesz?

**Comment by sandorkertesz** [comment]
I would replace all its internal usage with to_numpy(). I'd rather keep the code simple, one less function to maintain.

**Comment by sandorkertesz** [comment]
It has been decided to keep both the values property and to_numpy() and in the latter the default value will be flatten=False.
